ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      WRITE(*,*)  ' External Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_gedP = ', MDL_GEDP
      WRITE(*,*) 'mdl_gdFdP = ', MDL_GDFDP
      WRITE(*,*) 'aEWM1 = ', AEWM1
      WRITE(*,*) 'mdl_MdP = ', MDL_MDP
      WRITE(*,*) 'mdl_Me = ', MDL_ME
      WRITE(*,*) 'mdl_MdF = ', MDL_MDF
      WRITE(*,*) 'mdl_WdP = ', MDL_WDP
      WRITE(*,*)  ' Internal Params'
      WRITE(*,*)  ' ---------------------------------'
      WRITE(*,*)  ' '
      WRITE(*,*) 'mdl_complexi = ', MDL_COMPLEXI
      WRITE(*,*) 'mdl_eEM = ', MDL_EEM
      WRITE(*,*) 'aS = ', AS
      WRITE(*,*) 'G = ', G
      WRITE(*,*)  ' Internal Params evaluated point by point'
      WRITE(*,*)  ' ----------------------------------------'
      WRITE(*,*)  ' '

