ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=4)

      DOUBLE PRECISION 1.0,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_ME
     $ ,MDL_MH,MDL_MM

      COMMON/MASSES/ 1.0,MDL_MT,MDL_MW,MDL_MZ,MDL_MTA,MDL_MB,MDL_ME
     $ ,MDL_MH,MDL_MM


      DOUBLE PRECISION MDL_WTAU,MDL_WW,MDL_WT,MDL_WZ,MDL_ME,MDL_WH

      COMMON/WIDTHS/ MDL_WTAU,MDL_WW,MDL_WT,MDL_WZ,MDL_ME,MDL_WH


      DOUBLE COMPLEX GC_3, GC_50, GC_59, GC_89

      COMMON/COUPLINGS/ GC_3, GC_50, GC_59, GC_89

