ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
c      written by the UFO converter
ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc

      DOUBLE PRECISION G
      COMMON/STRONG/ G

      DOUBLE COMPLEX GAL(2)
      COMMON/WEAK/ GAL

      DOUBLE PRECISION MU_R
      COMMON/RSCALE/ MU_R

      DOUBLE PRECISION NF
      PARAMETER(NF=0)

      DOUBLE PRECISION MDL_MDF,MDL_ME,MDL_MDP

      COMMON/MASSES/ MDL_MDF,MDL_ME,MDL_MDP


      DOUBLE PRECISION MDL_WDP

      COMMON/WIDTHS/ MDL_WDP


      DOUBLE COMPLEX GC_1

      COMMON/COUPLINGS/ GC_1

